.TH QALC 1 "28 December 2008"
.SH NAME
qalculate-gtk \- Powerful and easy to use desktop calculator
.SH SYNOPSIS
.B qalculate-gtk
.SH DESCRIPTION
Qalculate! is a small and simple to use calculator but with much power and
versatility underneath. Features include customizable functions, units,
arbitrary precision using a one-line fault-tolerant expression entry.
.PP
\fBqalculate-gtk\fP is the GTK version of Qalculate!.
.SH AUTHORS
qalculate-gtk was written by Hanna Knutsson <hanna.knutsson@protonmail.com>.
.PP
This manual page was originally written by Vincent Legout <vincent@legout.info>,
for the Debian system (but may be used by others).
